import { useState } from "react";
import { api } from "../api/client";
import { asUTC } from "../utils/time";
import {
  PageHero, StatTiles, StatTile, SectionLabel, Loading, ErrorState, Empty,
  DetailDrawer, Badge, useAsync,
} from "../components/ui";
import Markdown from "../components/Markdown";
import type { ReportBrief, ReportDetail } from "../types";

const REPORTS_ICON = (
  <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor"
    strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">
    <path d="M7 3h7l5 5v13H7z" /><path d="M14 3v5h5M10 13h6M10 17h6M10 9h2" />
  </svg>
);

function when(iso: string | null): string {
  if (!iso) return "";
  const t = new Date(asUTC(iso)).getTime();
  if (!t) return "";
  return new Date(t).toLocaleString();
}

function sourceLabel(s?: string | null): string {
  if (!s) return "report";
  if (s === "workflow") return "Workflow";
  if (s === "tool") return "Tool";
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export default function Reports() {
  const list = useAsync<{ reports: ReportBrief[]; total: number }>(
    () => api.reports(100, 0) as Promise<{ reports: ReportBrief[]; total: number }>);
  const [openId, setOpenId] = useState<string | null>(null);
  const [detail, setDetail] = useState<ReportDetail | null>(null);
  const [detailLoading, setDetailLoading] = useState(false);
  const [detailErr, setDetailErr] = useState<string | null>(null);

  const open = (id: string) => {
    setOpenId(id); setDetail(null); setDetailErr(null); setDetailLoading(true);
    api.report(id)
      .then((r) => setDetail(r as ReportDetail))
      .catch((e) => setDetailErr(e?.message || "Could not load this report."))
      .finally(() => setDetailLoading(false));
  };

  const rows = list.data?.reports ?? [];
  const fromWorkflow = rows.filter((r) => r.source_type === "workflow").length;
  const fromTool = rows.filter((r) => r.source_type === "tool").length;

  return (
    <div className="page">
      <PageHero
        icon={REPORTS_ICON}
        eyebrow="AUTOMATION"
        title="Reports"
        desc="Local artifacts your governed workflows produce — operations reports, daily briefs, and tool outputs. Generated on this machine, readable here, never uploaded."
        actions={<button className="btn" style={{ width: "auto" }} onClick={list.reload}>Refresh</button>}
      />

      {rows.length > 0 && (
        <StatTiles>
          <StatTile label="TOTAL" value={list.data?.total ?? rows.length} hint="reports on file" />
          <StatTile label="FROM WORKFLOWS" value={fromWorkflow} hint="generated by automation" tone="accent" />
          <StatTile label="FROM TOOLS" value={fromTool} hint="emitted by a tool run" tone="violet" />
        </StatTiles>
      )}

      <SectionLabel hint={<a className="link" href="/workflows">Run a workflow →</a>}>ALL REPORTS</SectionLabel>

      {list.loading ? (
        <Loading rows={5} />
      ) : list.error ? (
        <ErrorState message={list.error} onRetry={list.reload} />
      ) : rows.length === 0 ? (
        <Empty
          icon={REPORTS_ICON}
          title="No reports yet"
          hint="Reports appear here when a workflow like “generate_local_report” or “create_daily_brief” runs. Trigger one from the Workflows page to produce your first local report."
          actions={<a className="btn btn-primary" style={{ width: "auto" }} href="/workflows">Go to Workflows</a>}
        />
      ) : (
        <div className="card-list">
          {rows.map((r) => (
            <div key={r.id} className="card-row clickable" onClick={() => open(r.id)}>
              <span className="card-row-meta" style={{ color: "var(--accent-2)" }}>{REPORTS_ICON}</span>
              <div className="card-row-main">
                <div className="card-row-title">{r.title || "Untitled report"}</div>
                <div className="card-row-sub">{sourceLabel(r.source_type)} · {when(r.created_at)}</div>
              </div>
              <div className="card-row-meta">
                <Badge tone="muted">{r.status}</Badge>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                  strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" style={{ opacity: 0.5 }}>
                  <path d="M9 6l6 6-6 6" />
                </svg>
              </div>
            </div>
          ))}
        </div>
      )}

      <DetailDrawer open={!!openId} onClose={() => setOpenId(null)} title="Report">
        {detailLoading ? <Loading rows={4} />
          : detailErr ? <ErrorState message={detailErr} onRetry={() => openId && open(openId)} />
          : detail ? (
            <>
              <h3 style={{ marginBottom: 4 }}>{detail.title}</h3>
              <div className="muted small" style={{ marginBottom: 14 }}>
                {sourceLabel(detail.source_type)} · {when(detail.created_at)}
                {detail.created_by ? ` · ${detail.created_by}` : ""}
              </div>
              <div className="md"><Markdown text={detail.content || "(empty report)"} /></div>
            </>
          ) : <Empty title="Select a report" hint="Choose a report from the list to read it." />}
      </DetailDrawer>
    </div>
  );
}
